#pragma once
#include <stdint.h>
#include "esp_err.h"
void system_init(void);
void i2c_bus_init(void);
void *get_i2c_bus_handle(void);
uint8_t tca9554_read_input(void);
void board_power_audio_on(void);
void board_power_audio_off(void);
bool system_tca9554_present(void);
